# Detecting noisy monitors

This notebook shows how to detect noisy monitors in a dataset using the WhyLabs Monitor Diagnoser. It uses the diagnoser to automatically detect the noisiest monitor for dataset, get a diagnosis of
the conditions causing the noise, get recommended changes and where automatable, apply those changes.

## Install requirements

In [5]:
# %pip install whylabs-toolkit[diagnoser]

## Setup whylabs API connection

First, set up the information to connect to WhyLabs. Update the org_id, dataset_id and api_key in the following before running it.

In [6]:
import getpass
from whylabs_toolkit.monitor.diagnoser.helpers.utils import env_setup

org_id = input("Enter org ID")
dataset_id = input("Enter model/dataset ID")
api_key = getpass.getpass("Enter API key")
api_endpoint = 'https://api.whylabsapp.com'

env_setup(
    org_id=org_id,
    dataset_id=dataset_id,
    api_key=api_key,
    whylabs_endpoint=api_endpoint
)

Initialize the Monitor Diagnoser with the org_id and dataset_id.

In [7]:
from whylabs_toolkit.monitor.diagnoser.monitor_diagnoser import MonitorDiagnoser
diagnoser = MonitorDiagnoser(org_id, dataset_id)

## Run the default diagnosis

With no further input, the diagnoser will make a series of calls to identify the noisiest monitor, segment and columns; and then perform a diagnosis.

In [8]:
monitor_report = diagnoser.diagnose()
monitor_report

MonitorDiagnosisReport(orgId='org-0', datasetId='model-0', analyzerId='frequent-items-drift-analyzer-x2hr9z', interval='2024-04-02T00:00:00.000Z/2024-05-02T00:00:00.000Z', expectedBatchCount=0, diagnosticData=DiagnosticDataSummary(diagnosticSegment=Segment(tags=[]), diagnosticProfile=ProfileSummary(minRowName='desc', minRowCount=1674392, maxRowName='desc', maxRowCount=1674392), diagnosticBatches=BatchesSummary(minBatchName='desc', minBatchCount=30, maxBatchName='desc', maxBatchCount=30), analysisResults=AnalysisResultsSummary(results=ResultRecord(diagnosedColumnCount=26, batchCount=30), failures=FailureRecord(totalFailuresCount=0, maxFailuresCount=0, meanFailuresCount=0, byColumnCount=[], byTypeCount=[]), anomalies=AnomalyRecord(totalAnomalyCount=34, maxAnomalyCount=30, meanAnomalyCount=11, batchCount=30, byColumnCount=[NamedCount(name='issue_d', count=30), NamedCount(name='url', count=3), NamedCount(name='desc', count=1)], byColumnBatchCount=[NamedCount(name='addr_state', count=30), NamedCount(name='application_type', count=30), NamedCount(name='debt_settlement_flag', count=30), NamedCount(name='desc', count=2), NamedCount(name='disbursement_method', count=30), NamedCount(name='earliest_cr_line', count=30), NamedCount(name='emp_length', count=30), NamedCount(name='emp_title', count=30), NamedCount(name='grade', count=30), NamedCount(name='hardship_flag', count=30), NamedCount(name='home_ownership', count=30), NamedCount(name='initial_list_status', count=30), NamedCount(name='issue_d', count=30), NamedCount(name='last_credit_pull_d', count=30), NamedCount(name='last_pymnt_d', count=30), NamedCount(name='loan_status', count=30), NamedCount(name='next_pymnt_d', count=30), NamedCount(name='purpose', count=30), NamedCount(name='pymnt_plan', count=30), NamedCount(name='sub_grade', count=30), NamedCount(name='term', count=30), NamedCount(name='title', count=30), NamedCount(name='url', count=30), NamedCount(name='verification_status', count=30), NamedCount(name='verification_status_joint', count=30), NamedCount(name='zip_code', count=30)])), targetedColumnCount=27), qualityIssues=[QualityIssueRecord(name='analyzer_changed', description='Analyzer changed within the diagnostic interval', detectors=['stale_analysis', 'changing_discrete', 'low_drift_threshold', 'missing_baseline_batches', 'small_nonnull_batches'])], conditions=[ConditionRecord(columns=['desc', 'issue_d', 'url'], info=None, summary='many values are unique across batches', name='changing_discrete'), ConditionRecord(columns=['desc'], info=None, summary='less than 500 non-null records in 50% or more of the batches', name='small_nonnull_batches')], monitor=Monitor(metadata=Metadata(version=1, schemaVersion=1, updatedTimestamp=1705536890090, author='user_809f777d_3741_4991_8ced_42f09b883ac7', description=None), id='frequent-items-drift-monitor-x2hr9z', displayName=None, tags=None, analyzerIds=['frequent-items-drift-analyzer-x2hr9z'], schedule=ImmediateSchedule(type='immediate'), disabled=False, severity=3, mode=DigestMode(type='DIGEST', filter=None, creationTimeOffset=None, datasetTimestampOffset=None, groupBy=None), actions=[GlobalAction(type='global', target='email')]), analyzer=Analyzer(metadata=Metadata(version=4, schemaVersion=1, updatedTimestamp=1714763295788, author='user_c9292ec40407f7b580f0a2c90745ebfba2b9e6ea81c848ef944d31e48a45f98', description=None), id='frequent-items-drift-analyzer-x2hr9z', displayName=None, tags=None, schedule=FixedCadenceSchedule(type='fixed', cadence=<Cadence.daily: 'daily'>, exclusionRanges=None), disabled=None, disableTargetRollup=None, targetMatrix=ColumnMatrix(segments=[Segment(tags=[])], type=<TargetLevel.column: 'column'>, include=[<ColumnGroups.group_discrete: 'group:discrete'>], exclude=['desc', <ColumnGroups.group_output: 'group:output'>, 'issue_d', 'url'], profileId=None), dataReadinessDuration=None, batchCoolDownPeriod=None, backfillGracePeriodDuration=None, config=DriftConfig(schemaVersion=None, params=None, metric=<ComplexMetrics.frequent_items: 'frequent_items'>, type=<AlgorithmType.drift: 'drift'>, algorithm='hellinger', threshold=0.7, minBatchSize=1, baseline=TrailingWindowBaseline(datasetId=None, inheritSegment=None, type=<BaselineType.TrailingWindow: 'TrailingWindow'>, size=7, offset=None, exclusionRanges=None))), analyzedColumnCount=26)

In [9]:
print(monitor_report.describe())

Diagnosis is for monitor "frequent-items-drift-monitor-x2hr9z" [frequent-items-drift-monitor-x2hr9z] in model-0 org-0, over interval 2024-04-02T00:00:00.000Z/2024-05-02T00:00:00.000Z.
Monitor has 1 notification actions ['email'].

Analyzer is drift configuration for frequent_items metric with TrailingWindow baseline.
Analyzer "frequent-items-drift-analyzer-x2hr9z" targets 27 columns and ran on 26 columns in the diagnosed segment.


Diagnostic segment is "overall".
Diagnostic interval contains 30 batches.

Diagnostic interval rollup contains 1674392 rows for the diagnosed columns.

Analysis results summary:
Found non-failed results for 26 columns and 30 batches.
Found 34 anomalies in 3 columns, with up to 100.0% (30) batches having anomalies per column and 36.7% (11.0) on average.
Columns with anomalies are:
|    | 0               |
|---:|:----------------|
|  0 | ('issue_d', 30) |
|  1 | ('url', 3)      |
|  2 | ('desc', 1)     |

No failures were detected.

Conditions that may impact diagnosis quality include:
	* analyzer_changed: Analyzer changed within the diagnostic interval - detectors ['stale_analysis', 'changing_discrete', 'low_drift_threshold', 'missing_baseline_batches', 'small_nonnull_batches']

Conditions that may contribute to noise include:
	* Condition changing_discrete (many values are unique across batches) for 3 columns: ['desc', 'issue_d', 'url']
	* Condition small_nonnull_batches (less than 500 non-null records in 50% or more of the batches) for 1 columns: ['desc']

Anomalies for columns with these conditions:
|      |   0 |
|:-----|----:|
| desc |   1 |
Accounting for 1 anomalies out of 34

The monitor report can be serialized to a JSON file for later use.

In [10]:
with open('monitor_report.json', 'w') as f:
    f.write(monitor_report.json())

In [11]:
from whylabs_toolkit.monitor.diagnoser.models import MonitorDiagnosisReport

with open('monitor_report.json', 'r') as f:
    monitor_report = MonitorDiagnosisReport.parse_raw(f.read())
print(monitor_report.json(indent=2))

{
  "orgId": "org-0",
  "datasetId": "model-0",
  "analyzerId": "frequent-items-drift-analyzer-x2hr9z",
  "interval": "2024-04-02T00:00:00.000Z/2024-05-02T00:00:00.000Z",
  "expectedBatchCount": 0,
  "diagnosticData": {
    "diagnosticSegment": {
      "tags": []
    },
    "diagnosticProfile": {
      "minRowName": "desc",
      "minRowCount": 1674392,
      "maxRowName": "desc",
      "maxRowCount": 1674392
    },
    "diagnosticBatches": {
      "minBatchName": "desc",
      "minBatchCount": 30,
      "maxBatchName": "desc",
      "maxBatchCount": 30
    },
    "analysisResults": {
      "results": {
        "diagnosedColumnCount": 26,
        "batchCount": 30
      },
      "failures": {
        "totalFailuresCount": 0,
        "maxFailuresCount": 0,
        "meanFailuresCount": 0,
        "byColumnCount": [],
        "byTypeCount": []
      },
      "anomalies": {
        "totalAnomalyCount": 34,
        "maxAnomalyCount": 30,
        "meanAnomalyCount": 11,
        "batchCount": 30,
        "byColumnCount": [
          {
            "name": "issue_d",
            "count": 30
          },
          {
            "name": "url",
            "count": 3
          },
          {
            "name": "desc",
            "count": 1
          }
        ],
        "byColumnBatchCount": [
          {
            "name": "addr_state",
            "count": 30
          },
          {
            "name": "application_type",
            "count": 30
          },
          {
            "name": "debt_settlement_flag",
            "count": 30
          },
          {
            "name": "desc",
            "count": 2
          },
          {
            "name": "disbursement_method",
            "count": 30
          },
          {
            "name": "earliest_cr_line",
            "count": 30
          },
          {
            "name": "emp_length",
            "count": 30
          },
          {
            "name": "emp_title",
            "count": 30
          },
          {
            "name": "grade",
            "count": 30
          },
          {
            "name": "hardship_flag",
            "count": 30
          },
          {
            "name": "home_ownership",
            "count": 30
          },
          {
            "name": "initial_list_status",
            "count": 30
          },
          {
            "name": "issue_d",
            "count": 30
          },
          {
            "name": "last_credit_pull_d",
            "count": 30
          },
          {
            "name": "last_pymnt_d",
            "count": 30
          },
          {
            "name": "loan_status",
            "count": 30
          },
          {
            "name": "next_pymnt_d",
            "count": 30
          },
          {
            "name": "purpose",
            "count": 30
          },
          {
            "name": "pymnt_plan",
            "count": 30
          },
          {
            "name": "sub_grade",
            "count": 30
          },
          {
            "name": "term",
            "count": 30
          },
          {
            "name": "title",
            "count": 30
          },
          {
            "name": "url",
            "count": 30
          },
          {
            "name": "verification_status",
            "count": 30
          },
          {
            "name": "verification_status_joint",
            "count": 30
          },
          {
            "name": "zip_code",
            "count": 30
          }
        ]
      }
    },
    "targetedColumnCount": 27
  },
  "qualityIssues": [
    {
      "name": "analyzer_changed",
      "description": "Analyzer changed within the diagnostic interval",
      "detectors": [
        "stale_analysis",
        "changing_discrete",
        "low_drift_threshold",
        "missing_baseline_batches",
        "small_nonnull_batches"
      ]
    }
  ],
  "conditions": [
    {
      "columns": [
        "desc",
        "issue_d",
        "url"
      ],
      "info": null,
      "summary": "many values are unique across batches",
      "name": "changing_discrete"
    },
    {
      "columns": [
        "desc"
      ],
      "info": null,
      "summary": "less than 500 non-null records in 50% or more of the batches",
      "name": "small_nonnull_batches"
    }
  ],
  "monitor": {
    "metadata": {
      "version": 1,
      "schemaVersion": 1,
      "updatedTimestamp": 1705536890090,
      "author": "user_809f777d_3741_4991_8ced_42f09b883ac7",
      "description": null
    },
    "id": "frequent-items-drift-monitor-x2hr9z",
    "displayName": null,
    "tags": null,
    "analyzerIds": [
      "frequent-items-drift-analyzer-x2hr9z"
    ],
    "schedule": {
      "type": "immediate"
    },
    "disabled": false,
    "severity": 3,
    "mode": {
      "type": "DIGEST",
      "filter": null,
      "creationTimeOffset": null,
      "datasetTimestampOffset": null,
      "groupBy": null
    },
    "actions": [
      {
        "type": "global",
        "target": "email"
      }
    ]
  },
  "analyzer": {
    "metadata": {
      "version": 4,
      "schemaVersion": 1,
      "updatedTimestamp": 1714763295788,
      "author": "user_c9292ec40407f7b580f0a2c90745ebfba2b9e6ea81c848ef944d31e48a45f98",
      "description": null
    },
    "id": "frequent-items-drift-analyzer-x2hr9z",
    "displayName": null,
    "tags": null,
    "schedule": {
      "type": "fixed",
      "cadence": "daily",
      "exclusionRanges": null
    },
    "disabled": null,
    "disableTargetRollup": null,
    "targetMatrix": {
      "segments": [
        {
          "tags": []
        }
      ],
      "type": "column",
      "include": [
        "group:discrete"
      ],
      "exclude": [
        "desc",
        "group:output",
        "issue_d",
        "url"
      ],
      "profileId": null
    },
    "dataReadinessDuration": null,
    "batchCoolDownPeriod": null,
    "backfillGracePeriodDuration": null,
    "config": {
      "schemaVersion": null,
      "params": null,
      "metric": "frequent_items",
      "type": "drift",
      "algorithm": "hellinger",
      "threshold": 0.7,
      "minBatchSize": 1,
      "baseline": {
        "datasetId": null,
        "inheritSegment": null,
        "type": "TrailingWindow",
        "size": 7,
        "offset": null,
        "exclusionRanges": null
      }
    }
  },
  "analyzedColumnCount": 26
}

## Ask for recommended changes

Given the diagnosis report for the monitor, the ChangeRecommender will recommend changes to make to the monitor. By default it will make recommendations for all columns where it has detected noise-related conditions. Set the `min_anomaly_count` property to restrict this to only columns that caused a certain number of anomalies.

In [12]:
from whylabs_toolkit.monitor.diagnoser.recommendation.change_recommender import ChangeRecommender

recommender = ChangeRecommender(monitor_report)
recommender.min_anomaly_count = 1
changes = recommender.recommend()
print('\n'.join([f'{i+1}. {c.describe()}' for i, c in enumerate(changes)]))

1. Remove columns from the analyzer for ['desc', 'issue_d', 'url']
2. Make a manual change to the analyzer to address small_nonnull_batches: less than 500 non-null records in 50% or more of the batches for ['desc']

## Execute automatable changes

A subset of recommended changes can be executed automatically by the recommender. Pass the ones you want to make into the `make_changes` call, or pass all changes if you want it to make all of the automatable changes.

In [13]:
automatable_changes = [c for c in changes if c.can_automate()]
print('\n'.join([c.describe() for c in automatable_changes]))

Remove columns from the analyzer for ['desc', 'issue_d', 'url']

In [14]:
change_results = recommender.make_changes(automatable_changes)
print(change_results.describe())

Successfully made the following changes:
	* Remove columns from the analyzer for ['desc', 'issue_d', 'url']

Note that the monitor will still appear to the diagnoser as the noisiest monitor until enough time has passed for the impact of the monitor changes to be observed. You may want to use the WhyLabs preview UI to view what impacts may be expected from the change.

## Reviewing other noisy monitors

The diagnoser can be used to review other noisy monitors in the dataset. The `noisy_monitors` property will return a list of the noisiest monitors, and the `monitor_id_to_diagnose` property can be set to the monitor_id of the monitor to diagnose.

In [15]:
import pandas as pd
noisy_monitors_df = pd.DataFrame.from_records([m.dict() for m in diagnoser.noisy_monitors])
noisy_monitors_df

,monitor_id,analyzer_id,metric,column_count,segment_count,anomaly_count,max_anomaly_per_column,min_anomaly_per_column,avg_anomaly_per_column,action_count,action_targets
0,frequent-items-drift-monitor-x2hr9z,frequent-items-drift-analyzer-x2hr9z,frequent_items,3,1,34,30,1,11,1,[email]
1,discrete-distribution-22ef37c9-monitor,discrete-distribution-22ef37c9,frequent_items,3,1,34,30,1,11,0,[]
2,smoggy-chartreuse-owl-3387,smoggy-chartreuse-owl-3387-analyzer,frequent_items,3,1,34,30,1,11,0,[]
3,frequent-items-drift-monitor-bx6m80,frequent-items-drift-analyzer-bx6m80,frequent_items,3,1,34,30,1,11,0,[]
4,frequent-items-drift-monitor-mat0jo,frequent-items-drift-analyzer-mat0jo,frequent_items,3,1,34,30,1,11,2,"[email, slack]"
5,frequent-items-drift-monitor-01rbfl,frequent-items-drift-analyzer-01rbfl,frequent_items,3,1,34,30,1,11,1,[email]
6,frequent-items-drift-monitor-0foigt,frequent-items-drift-analyzer-0foigt,frequent_items,3,1,34,30,1,11,0,[]
7,frequent-items-drift-monitor-3c0hc2,frequent-items-drift-analyzer-3c0hc2,frequent_items,3,1,34,30,1,11,1,[email]
8,frequent-items-drift-monitor-9gmtix,frequent-items-drift-analyzer-9gmtix,frequent_items,3,1,34,30,1,11,1,[email]
9,elated-palegreen-jaguar-6432,elated-palegreen-jaguar-6432-analyzer,histogram,9,1,75,19,2,8,0,[]
10,inferred-data-type-fec5a735-monitor,inferred-data-type-fec5a735,inferred_data_type,1,1,14,14,14,14,2,"[email, slack]"
11,unique-ratio-b7b84aee-monitor,unique-ratio-b7b84aee,unique_est_ratio,69,1,104,4,1,1,0,[]
12,missing-values-ratio-35881327-monitor,missing-values-ratio-35881327,count_null_ratio,21,1,27,3,1,1,0,[]
13,numerical-drift-monitor-6oxi83,numerical-drift-analyzer-6oxi83,histogram,1,1,2,2,2,2,0,[]
14,numerical-drift-monitor-8yugth,numerical-drift-analyzer-8yugth,histogram,1,1,2,2,2,2,0,[]
15,continuous-distribution-956a280c-monitor,continuous-distribution-956a280c,histogram,1,1,2,2,2,2,0,[]
16,dull-floralwhite-raven-5521,dull-floralwhite-raven-5521-analyzer,count,2,1,3,2,1,1,0,[]

In [16]:
diagnoser.monitor_id_to_diagnose = noisy_monitors_df.iloc[1]['monitor_id']
print(diagnoser.monitor_id_to_diagnose)
monitor_report = diagnoser.diagnose()
print(monitor_report.describe())

discrete-distribution-22ef37c9-monitor
Diagnosis is for monitor "discrete-distribution-22ef37c9-monitor" [discrete-distribution-22ef37c9-monitor] in model-0 org-0, over interval 2024-04-02T00:00:00.000Z/2024-05-02T00:00:00.000Z.

Analyzer is drift configuration for frequent_items metric with TrailingWindow baseline.
Analyzer "discrete-distribution-22ef37c9" targets 30 columns and ran on 26 columns in the diagnosed segment.


Diagnostic segment is "overall".
Diagnostic interval contains 30 batches.

Diagnostic interval rollup contains 1674392 rows for the diagnosed columns.

Analysis results summary:
Found non-failed results for 26 columns and 30 batches.
Found 34 anomalies in 3 columns, with up to 100.0% (30) batches having anomalies per column and 36.7% (11.0) on average.
Columns with anomalies are:
|    | 0               |
|---:|:----------------|
|  0 | ('issue_d', 30) |
|  1 | ('url', 3)      |
|  2 | ('desc', 1)     |

No failures were detected.

Conditions that may impact diagnosis quality include:
	* analyzer_changed: Analyzer changed within the diagnostic interval - detectors ['stale_analysis', 'changing_discrete', 'low_drift_threshold', 'missing_baseline_batches', 'small_nonnull_batches']

Conditions that may contribute to noise include:
	* Condition changing_discrete (many values are unique across batches) for 3 columns: ['desc', 'issue_d', 'url']
	* Condition small_nonnull_batches (less than 500 non-null records in 50% or more of the batches) for 1 columns: ['desc']

Anomalies for columns with these conditions:
|      |   0 |
|:-----|----:|
| desc |   1 |
Accounting for 1 anomalies out of 34

You can also use the `noisy_monitors_with_actions` property to prioritize noise in monitors with actions, as these are most likely to cause alert fatigue.

In [17]:
pd.DataFrame.from_records([m.dict() for m in diagnoser.noisy_monitors_with_actions])

,monitor_id,analyzer_id,metric,column_count,segment_count,anomaly_count,max_anomaly_per_column,min_anomaly_per_column,avg_anomaly_per_column,action_count,action_targets
0,frequent-items-drift-monitor-x2hr9z,frequent-items-drift-analyzer-x2hr9z,frequent_items,3,1,34,30,1,11,1,[email]
1,frequent-items-drift-monitor-mat0jo,frequent-items-drift-analyzer-mat0jo,frequent_items,3,1,34,30,1,11,2,"[email, slack]"
2,frequent-items-drift-monitor-01rbfl,frequent-items-drift-analyzer-01rbfl,frequent_items,3,1,34,30,1,11,1,[email]
3,frequent-items-drift-monitor-3c0hc2,frequent-items-drift-analyzer-3c0hc2,frequent_items,3,1,34,30,1,11,1,[email]
4,frequent-items-drift-monitor-9gmtix,frequent-items-drift-analyzer-9gmtix,frequent_items,3,1,34,30,1,11,1,[email]
5,inferred-data-type-fec5a735-monitor,inferred-data-type-fec5a735,inferred_data_type,1,1,14,14,14,14,2,"[email, slack]"